// src/lib/surah-data.ts

export const SURAH_DATA = [
  { number: 1, name: "Al-Fatihah", arti: "Pembukaan" },
  { number: 2, name: "Al-Baqarah", arti: "Sapi Betina" },
  { number: 3, name: "Ali 'Imran", arti: "Keluarga Imran" },
  { number: 4, name: "An-Nisa'", arti: "Wanita" },
  { number: 5, name: "Al-Ma'idah", arti: "Hidangan" },
  { number: 6, name: "Al-An'am", arti: "Binatang Ternak" },
  { number: 7, name: "Al-A'raf", arti: "Tempat Tertinggi" },
  { number: 8, name: "Al-Anfal", arti: "Rampasan Perang" },
  { number: 9, name: "At-Taubah", arti: "Pengampunan" },
  { number: 10, name: "Yunus", arti: "Nabi Yunus" },
  { number: 11, name: "Hud", arti: "Nabi Hud" },
  { number: 12, name: "Yusuf", arti: "Nabi Yusuf" },
  { number: 13, name: "Ar-Ra'd", arti: "Guruh" },
  { number: 14, name: "Ibrahim", arti: "Nabi Ibrahim" },
  { number: 15, name: "Al-Hijr", arti: "Bukit Pasir" },
  { number: 16, name: "An-Nahl", arti: "Lebah" },
  { number: 17, name: "Al-Isra'", arti: "Perjalanan Malam" },
  { number: 18, name: "Al-Kahf", arti: "Gua" },
  { number: 19, name: "Maryam", arti: "Maryam" },
  { number: 20, name: "Ta-Ha", arti: "Ta-Ha" },
  { number: 21, name: "Al-Anbiya'", arti: "Para Nabi" },
  { number: 22, name: "Al-Hajj", arti: "Haji" },
  { number: 23, name: "Al-Mu'minun", arti: "Orang-orang Mukmin" },
  { number: 24, name: "An-Nur", arti: "Cahaya" },
  { number: 25, name: "Al-Furqan", arti: "Pembeda" },
  { number: 26, name: "Asy-Syua'ra'", arti: "Para Penyair" },
  { number: 27, name: "An-Naml", arti: "Semut" },
  { number: 28, name: "Al-Qasas", arti: "Kisah-kisah" },
  { number: 29, name: "Al-Ankabut", arti: "Laba-laba" },
  { number: 30, name: "Ar-Rum", arti: "Bangsa Romawi" },
  { number: 31, name: "Luqman", arti: "Luqman" },
  { number: 32, name: "As-Sajdah", arti: "Sujud" },
  { number: 33, name: "Al-Ahzab", arti: "Golongan yang Bersekutu" },
  { number: 34, name: "Saba'", arti: "Kaum Saba'" },
  { number: 35, name: "Fatir", arti: "Pencipta" },
  { number: 36, name: "Ya-Sin", arti: "Ya-Sin" },
  { number: 37, name: "As-Saffat", arti: "Barisan-barisan" },
  { number: 38, name: "Sad", arti: "Sad" },
  { number: 39, name: "Az-Zumar", arti: "Rombongan-rombongan" },
  { number: 40, name: "Ghafir", arti: "Yang Mengampuni" },
  { number: 41, name: "Fussilat", arti: "Yang Dijelaskan" },
  { number: 42, name: "Asy-Syura", arti: "Musyawarah" },
  { number: 43, name: "Az-Zukhruf", arti: "Perhiasan" },
  { number: 44, name: "Ad-Dukhan", arti: "Kabut" },
  { number: 45, name: "Al-Jasiyah", arti: "Yang Berlutut" },
  { number: 46, name: "Al-Ahqaf", arti: "Bukit-bukit Pasir" },
  { number: 47, name: "Muhammad", arti: "Nabi Muhammad" },
  { number: 48, name: "Al-Fath", arti: "Kemenangan" },
  { number: 49, name: "Al-Hujurat", arti: "Kamar-kamar" },
  { number: 50, name: "Qaf", arti: "Qaf" },
  { number: 51, name: "Az-Zariyat", arti: "Angin yang Menerbangkan" },
  { number: 52, name: "At-Tur", arti: "Bukit" },
  { number: 53, name: "An-Najm", arti: "Bintang" },
  { number: 54, name: "Al-Qamar", arti: "Bulan" },
  { number: 55, name: "Ar-Rahman", arti: "Yang Maha Pemurah" },
  { number: 56, name: "Al-Waqi'ah", arti: "Hari Kiamat" },
  { number: 57, name: "Al-Hadid", arti: "Besi" },
  { number: 58, name: "Al-Mujadilah", arti: "Wanita yang Menggugat" },
  { number: 59, name: "Al-Hashr", arti: "Pengusiran" },
  { number: 60, name: "Al-Mumtahanah", arti: "Wanita yang Diuji" },
  { number: 61, name: "As-Saff", arti: "Barisan" },
  { number: 62, name: "Al-Jumu'ah", arti: "Hari Jumat" },
  { number: 63, name: "Al-Munafiqun", arti: "Orang-orang Munafik" },
  { number: 64, name: "At-Tagabun", arti: "Hari Ditampakkan Kesalahan" },
  { number: 65, name: "At-Talaq", arti: "Talak" },
  { number: 66, name: "At-Tahrim", arti: "Mengharamkan" },
  { number: 67, name: "Al-Mulk", arti: "Kerajaan" },
  { number: 68, name: "Al-Qalam", arti: "Pena" },
  { number: 69, name: "Al-Haqqah", arti: "Hari Kiamat" },
  { number: 70, name: "Al-Ma'arij", arti: "Tempat Naik" },
  { number: 71, name: "Nuh", arti: "Nabi Nuh" },
  { number: 72, name: "Al-Jinn", arti: "Jin" },
  { number: 73, name: "Al-Muzzammil", arti: "Orang yang Berselimut" },
  { number: 74, name: "Al-Muddassir", arti: "Orang yang Berkemul" },
  { number: 75, name: "Al-Qiyamah", arti: "Hari Kiamat" },
  { number: 76, name: "Al-Insan", arti: "Manusia" },
  { number: 77, name: "Al-Mursalat", arti: "Malaikat yang Diutus" },
  { number: 78, name: "An-Naba'", arti: "Berita Besar" },
  { number: 79, name: "An-Nazi'at", arti: "Malaikat Pencabut" },
  { number: 80, name: "Abasa", arti: "Ia Bermuka Masam" },
  { number: 81, name: "At-Takwir", arti: "Menggulung" },
  { number: 82, name: "Al-Infitar", arti: "Terbelah" },
  { number: 83, name: "Al-Mutaffifin", arti: "Orang-orang Curang" },
  { number: 84, name: "Al-Insyiqaq", arti: "Terbelah" },
  { number: 85, name: "Al-Buruj", arti: "Gugusan Bintang" },
  { number: 86, name: "At-Tariq", arti: "Yang Datang di Malam Hari" },
  { number: 87, name: "Al-A'la", arti: "Yang Paling Tinggi" },
  { number: 88, name: "Al-Ghasyiyah", arti: "Hari Pembalasan" },
  { number: 89, name: "Al-Fajr", arti: "Fajar" },
  { number: 90, name: "Al-Balad", arti: "Negeri" },
  { number: 91, name: "Asy-Syams", arti: "Matahari" },
  { number: 92, name: "Al-Lail", arti: "Malam" },
  { number: 93, name: "Ad-Duha", arti: "Waktu Duha" },
  { number: 94, name: "Al-Insyirah", arti: "Kelapangan" },
  { number: 95, name: "At-Tin", arti: "Buah Tin" },
  { number: 96, name: "Al-Alaq", arti: "Segumpal Darah" },
  { number: 97, name: "Al-Qadr", arti: "Kemuliaan" },
  { number: 98, name: "Al-Bayyinah", arti: "Bukti" },
  { number: 99, name: "Az-Zalzalah", arti: "Kegoncangan" },
  { number: 100, name: "Al-Adiyat", arti: "Kuda Perang" },
  { number: 101, name: "Al-Qari'ah", arti: "Hari Kiamat" },
  { number: 102, name: "At-Takasur", arti: "Bermegah-megahan" },
  { number: 103, name: "Al-Asr", arti: "Masa" },
  { number: 104, name: "Al-Humazah", arti: "Pengumpat" },
  { number: 105, name: "Al-Fil", arti: "Gajah" },
  { number: 106, name: "Quraisy", arti: "Suku Quraisy" },
  { number: 107, name: "Al-Ma'un", arti: "Barang-barang Berguna" },
  { number: 108, name: "Al-Kautsar", arti: "Nikmat yang Banyak" },
  { number: 109, name: "Al-Kafirun", arti: "Orang-orang Kafir" },
  { number: 110, name: "An-Nasr", arti: "Pertolongan" },
  { number: 111, name: "Al-Lahab", arti: "Gejolak Api" },
  { number: 112, name: "Al-Ikhlas", arti: "Ikhlas" },
  { number: 113, name: "Al-Falaq", arti: "Waktu Subuh" },
  { number: 114, name: "An-Nas", arti: "Manusia" }
]